#!/bin/sh
 
remote="$1"
url="$2"
 
while read local_ref local_sha remote_ref remote_sha
do
if [[ "$remote_ref" =~ ^.*/(master|main|develop)$ ]]; then
echo "[error] can't push to origin $remote_ref branch."
exit 1
fi
done
 
exit 0